bind_add = ":8080"
log_level = "info"
database_url = "host=db dbname=postgres sslmode=disable user=postgres password=pass"

[auth]
token_header = "Token"
auth_secret = "secret"
mfcc_url = "http://python-backend:8000/py/mfcc/"

[grpc]
bind_grpc_addr = ":9000"